models/Cambios.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "cambios".
 *
 * @property int $codigo_cambio
 * @property string|null $motivo_cambio
 * @property int|null $baja
 *
 * @property AlmacenesQueGestionanCambios[] $almacenesQueGestionanCambios
 * @property Almacenes[] $codigoAlmacens
 * @property ProductosQueSufrenCambios[] $productosQueSufrenCambios
 * @property Productos[] $codigoProductos
 */
class Cambios extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'cambios';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            'obligatorios'=>[['motivo_cambio'], 'required', 'message'=> 'Campo Obligatorio'],
            'baja' => ['baja', 'default', 'value'=>0],
            [['motivo_cambio'], 'match', 'pattern' => '/^[a-z]\w+(\s+\w+)*$/i'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'codigo_cambio' => 'Codigo Cambio',
            'motivo_cambio' => 'Motivo Cambio',
            'baja' => 'Baja',
        ];
    }

    /**
     * Gets query for [[AlmacenesQueGestionanCambios]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getAlmacenesQueGestionanCambios()
    {
        return $this->hasMany(AlmacenesQueGestionanCambios::className(), ['codigo_cambio' => 'codigo_cambio']);
    }

    /**
     * Gets query for [[CodigoAlmacens]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCodigoAlmacens()
    {
        return $this->hasMany(Almacenes::className(), ['codigo_almacen' => 'codigo_almacen'])->viaTable('almacenes_que_gestionan_cambios', ['codigo_cambio' => 'codigo_cambio']);
    }

    /**
     * Gets query for [[ProductosQueSufrenCambios]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getProductosQueSufrenCambios()
    {
        return $this->hasMany(ProductosQueSufrenCambios::className(), ['codigo_cambio' => 'codigo_cambio']);
    }

    /**
     * Gets query for [[CodigoProductos]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCodigoProductos()
    {
        return $this->hasMany(Productos::className(), ['codigo_producto' => 'codigo_producto'])->viaTable('productos_que_sufren_cambios', ['codigo_cambio' => 'codigo_cambio']);
    }
}

controllers/CambiosController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Cambios;
use app\models\CambiosSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\ActiveDataProvider;

/**
 * CambiosController implements the CRUD actions for Cambios model.
 */
class CambiosController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Cambios models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CambiosSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Cambios model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Cambios model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Cambios();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->codigo_cambio]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Cambios model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->codigo_cambio]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Cambios model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
   public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

     public function actionBaja($id)
    {
         Yii::$app->db->createCommand()
        ->update('cambios', ['baja'=>1], 'codigo_cambio='.$id)
        ->execute();
    return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }
    
    public function actionAlta($id)
    {
         Yii::$app->db->createCommand()
        ->update('cambios', ['baja'=>0], 'codigo_cambio='.$id)
        ->execute();
    return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }


    /**
     * Finds the Cambios model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Cambios the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Cambios::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
    
    public function actionCambioslogistica(){
        $dataProvider= new ActiveDataProvider([
            'query'=> Cambios::find()-> select("codigo_cambio, motivo_cambio")
            -> where ('baja=0'),
            'pagination'=>[
                'pageSize'=>5,
            ]
        ]);
        
        return $this-> render("cambioslogistica",[
            "resultados"=>$dataProvider,
            "campos"=>['codigo_cambio','motivo_cambio'],
            "titulo"=> "BASE DE DATOS GENERAL",
             "enunciado"=> "CASO DE USO UTILIZANDO ORM",
            "sql"=> "SELECT * FROM productos WHERE baja IS FALSE ",
            
        ]);
     }     
     
     public function actionCambioslogisticapapelera(){
        $dataProvider= new ActiveDataProvider([
            'query'=> Cambios::find()-> select("codigo_cambio, motivo_cambio")
            -> where ('baja=1'),
            'pagination'=>[
                'pageSize'=>5,
            ]
        ]);
        
        return $this-> render("cambioslogisticapapelera",[
            "resultados"=>$dataProvider,
            "campos"=>['codigo_cambio','motivo_cambio'],
            "titulo"=> "BASE DE DATOS GENERAL",
             "enunciado"=> "CASO DE USO UTILIZANDO ORM",
            "sql"=> "SELECT * FROM productos WHERE baja IS FALSE ",
            
        ]);
     }     
}

views/cambios/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Cambios */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="cambios-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'motivo_cambio', ['template' => '{label}
*{input}'])->textInput(['maxlength' => true]) ?>


    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-marta-guardar']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/cambios/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\CambiosSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="cambios-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'codigo_cambio') ?>

    <?= $form->field($model, 'motivo_cambio') ?>

    <?= $form->field($model, 'baja') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/cambios/cambioslogistica.php
<?php

/* @var $this yii\web\View */
/* @var $model app\models\Cambios */


use yii\helpers\Html;

$this->title = 'CAMBIOS';
$this->params['breadcrumbs'][] = ['label' => 'Logística: Menú', 'url' => ['site/menulogistica']];
$this->params['breadcrumbs'][] = $this->title;

?>

<div class="body-content">
    <br>
        <br>
        <div class="row">
            <div class="col-sm-4">
                <div class="thumbnail">
                     <?= Html::img('@web/images/cambiosalmacen.png', ['alt' => 'My logo']) ?>
                    
                </div>
            </div>
            <div class="col-sm-8">
                
                <div class="thumbnail">
                    
                    <h1>CAMBIOS DE PRODUCTOS EN ALMACEN</h1>
                    
                </div>
                
            </div>
        </div>
        
        <br>
        <br>
        
        <div class="row">
            
              <div class="col-sm-6">
             <p>
        <?= Html::a('Nuevo', ['cambios/create'], ['class' => 'btn btn-marta']) ?>
            
                      <?= Html::a('Papelera', ['cambios/cambioslogisticapapelera'], ['class' => 'btn btn-marta']) ?>
                 
                      <?= Html::a('Añadir comentario a cambio', ['comentarios/createcambios'], ['class' => 'btn btn-marta']) ?>
    </p>    
            </div>
        </div>
        
        <br>
        <br>
    </div>

<?= \yii\grid\GridView::widget([
    'dataProvider'=> $resultados,
     'columns' => [
//         ['class'=>'yii\grid\SerialColumn'],
//         'codigo_pedido',
         'motivo_cambio',
     ['class'=>'yii\grid\ActionColumn',
              'template' => '{view}, {baja}',
               'buttons' => [
            'view' => function ($url) {
              
                return Html::a('<span class="glyphicon glyphicon-eye-open"></span>',$url, [
                            'title' => Yii::t('app', 'lead-view')]);
            },
                   'baja' => function ($url) {
              
                return Html::a('<span class="glyphicon glyphicon-remove"></span>',$url, [
                            'title' => Yii::t('app', 'lead-baja'),
                    'data-confirm' => Yii::t('yii', 'Are you sure you want to update this item?'),
            'data-method'  => 'post']);
            } ],
                    'urlCreator' => function ($action, $model) {

    	if ($action === 'view') {

        	$url = './view?id='.$model['codigo_cambio'];

        	return $url;

    	}
                if ($action === 'baja') {

        	$url = './baja?id='.$model['codigo_cambio'];

        	return $url;

    	}


	}]
         
        ]]);?>

views/cambios/cambioslogisticapapelera.php
<?php

/* @var $this yii\web\View */
/* @var $model app\models\Cambios */


use yii\helpers\Html;

$this->title = 'CAMBIOS: PAPELERA';
$this->params['breadcrumbs'][] = ['label' => 'Logística: Menú', 'url' => ['site/menulogistica']];
$this->params['breadcrumbs'][] = ['label' => 'CAMBIOS', 'url' => ['cambios/cambioslogistica']];
$this->params['breadcrumbs'][] = $this->title;

?>

<div class="body-content">
    <br>
        <br>
        <div class="row">
            <div class="col-sm-4">
                <div class="thumbnail">
                     <?= Html::img('@web/images/cambiosalmacen.png', ['alt' => 'My logo']) ?>
                    
                </div>
            </div>
            <div class="col-sm-8">
                
                <div class="thumbnail">
                    
                    <h1>CAMBIOS DE PRODUCTOS EN ALMACEN: PAPELERA</h1>
                    
                </div>
                
            </div>
        </div>
        
        <br>
        <br>
    </div>
<?= \yii\grid\GridView::widget([
    'dataProvider'=> $resultados,
     'columns' => [
//         ['class'=>'yii\grid\SerialColumn'],
//         'codigo_pedido',
         'motivo_cambio',
        
     ['class'=>'yii\grid\ActionColumn',
              'template' => '{view}, {alta}, {delete}',
               'buttons' => [
            'view' => function ($url) {
              
                return Html::a('<span class="glyphicon glyphicon-eye-open"></span>',$url, [
                            'title' => Yii::t('app', 'lead-view')]);
            },
                   'alta' => function ($url) {
              
                return Html::a('<span class="glyphicon glyphicon-ok"></span>',$url, [
                            'title' => Yii::t('app', 'lead-alta'),
                    'data-confirm' => Yii::t('yii', 'Are you sure you want to update this item?'),
            'data-method'  => 'post']);
            },
                    'delete' => function ($url) {
              
                return Html::a('<span class="glyphicon glyphicon-trash"></span>',$url, [
                            'title' => Yii::t('app', 'lead-delete'),
                    'data-confirm' => Yii::t('yii', 'Are you sure you want to delete this item?'),
            'data-method'  => 'post']);
            } ],
                            
                    
                    'urlCreator' => function ($action, $model) {

    	if ($action === 'view') {

        	$url = './view?id='.$model['codigo_cambio'];

        	return $url;

    	}
                if ($action === 'alta') {

        	$url = './alta?id='.$model['codigo_cambio'];

        	return $url;

    	}
        if ($action === 'delete') {

        	$url = './delete?id='.$model['codigo_cambio'];

        	return $url;

    	}


	}]
         
        ]]);?>

views/cambios/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Cambios */

$this->title = 'ALTA CAMBIO';
$this->params['breadcrumbs'][] = ['label' => 'Logística: Menú', 'url' => ['site/menulogistica']];
$this->params['breadcrumbs'][] = ['label' => 'CAMBIOS', 'url' => ['cambios/cambioslogistica']];
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="cambios-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/cambios/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\CambiosSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Cambios';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="cambios-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Cambios', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'codigo_cambio',
            'motivo_cambio',
            'baja',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>


</div>

views/cambios/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Cambios */

$this->title = 'Update Cambios: ' . $model->codigo_cambio;
$this->params['breadcrumbs'][] = ['label' => 'Cambios', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->codigo_cambio, 'url' => ['view', 'id' => $model->codigo_cambio]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="cambios-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/cambios/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Cambios */

$this->title = $model->codigo_cambio;
$this->params['breadcrumbs'][] = ['label' => 'Logística: Menú', 'url' => ['site/menulogistica']];
$this->params['breadcrumbs'][] = ['label' => 'CAMBIOS', 'url' => ['cambios/cambioslogistica']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="cambios-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->codigo_cambio], ['class' => 'btn btn-marta']) ?>
<!--        Html::a('Delete', ['delete', 'id' => $model->codigo_cambio], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) -->
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'codigo_cambio',
            'motivo_cambio',
            'baja',
        ],
    ]) ?>

</div>