models/Clientes.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "clientes".
 *
 * @property int $codigo_cliente
 * @property string|null $pais_cliente
 * @property string|null $cif_cliente
 * @property string|null $nombre_cliente
 * @property string|null $tipo_empresa_cliente
 * @property string|null $sociedad_empresa_cliente
 * @property string|null $nombre_contacto_cliente
 * @property string|null $primer_apellido_contacto_cliente
 * @property string|null $segundo_apellido_contacto_cliente
 * @property int|null $baja
 *
 * @property Comentarios[] $comentarios
 * @property DireccionesEnvioClientes[] $direccionesEnvioClientes
 * @property DireccionesFacturacionClientes[] $direccionesFacturacionClientes
 * @property EmailsClientes[] $emailsClientes
 * @property Pedidos[] $pedidos
 * @property Proyectos[] $proyectos
 * @property TlfsClientes[] $tlfsClientes
 * @property Ventas[] $ventas
 * @property Productos[] $codProductos
 */
class Clientes extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'clientes';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            'obligatorios'=>[['nombre_cliente'], 'required', 'message'=> 'Campo Obligatorio'],
           'baja' => ['baja', 'default', 'value'=>0],
            'pais'=> ['pais_cliente', 'match', 'pattern' => '/^[a-z]\w+$/i', 'message'=> 'EL PAÍS HA DE SER INTRODUCIDO CON EL SIGUIENTE FORMATO: XX'],
            [['cif_cliente'], 'string', 'max' => 9],
            [['tipo_empresa_cliente', 'sociedad_empresa_cliente', 'nombre_contacto_cliente', 'primer_apellido_contacto_cliente', 'segundo_apellido_contacto_cliente'], 'match', 'pattern' => '/^[a-z]\w+(\s+\w+)*$/i'],
            'nombre_cliente'=>[['nombre_cliente'], 'match', 'pattern' => '/^[a-z]\w+(\s+\w+)*$/i', 'message'=> 'EL CAMPO HA DE SER UN NOMBRE VÁLIDO'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'codigo_cliente' => 'Codigo Cliente',
            'pais_cliente' => 'Pais Cliente',
            'cif_cliente' => 'Cif Cliente',
            'nombre_cliente' => 'Nombre Cliente',
            'tipo_empresa_cliente' => 'Tipo Empresa Cliente',
            'sociedad_empresa_cliente' => 'Sociedad Empresa Cliente',
            'nombre_contacto_cliente' => 'Nombre Contacto Cliente',
            'primer_apellido_contacto_cliente' => 'Primer Apellido Contacto Cliente',
            'segundo_apellido_contacto_cliente' => 'Segundo Apellido Contacto Cliente',
            'baja' => 'Baja',
        ];
    }

    /**
     * Gets query for [[Comentarios]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getComentarios()
    {
        return $this->hasMany(Comentarios::className(), ['codigo_cliente' => 'codigo_cliente']);
    }

    /**
     * Gets query for [[DireccionesEnvioClientes]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getDireccionesEnvioClientes()
    {
        return $this->hasMany(DireccionesEnvioClientes::className(), ['codigo_cliente' => 'codigo_cliente']);
    }

    /**
     * Gets query for [[DireccionesFacturacionClientes]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getDireccionesFacturacionClientes()
    {
        return $this->hasMany(DireccionesFacturacionClientes::className(), ['codigo_cliente' => 'codigo_cliente']);
    }

    /**
     * Gets query for [[EmailsClientes]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getEmailsClientes()
    {
        return $this->hasMany(EmailsClientes::className(), ['codigo_cliente' => 'codigo_cliente']);
    }

    /**
     * Gets query for [[Pedidos]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getPedidos()
    {
        return $this->hasMany(Pedidos::className(), ['codigo_cliente' => 'codigo_cliente']);
    }

    /**
     * Gets query for [[Proyectos]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getProyectos()
    {
        return $this->hasMany(Proyectos::className(), ['codigo_cliente' => 'codigo_cliente']);
    }

    /**
     * Gets query for [[TlfsClientes]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getTlfsClientes()
    {
        return $this->hasMany(TlfsClientes::className(), ['codigo_cliente' => 'codigo_cliente']);
    }

    /**
     * Gets query for [[Ventas]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getVentas()
    {
        return $this->hasMany(Ventas::className(), ['cod_cliente' => 'codigo_cliente']);
    }

    /**
     * Gets query for [[CodProductos]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCodProductos()
    {
        return $this->hasMany(Productos::className(), ['codigo_producto' => 'cod_producto'])->viaTable('ventas', ['cod_cliente' => 'codigo_cliente']);
    }
}

controllers/ClientesController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Clientes;
use app\models\ClientesSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\ActiveDataProvider;

/**
 * ClientesController implements the CRUD actions for Clientes model.
 */
class ClientesController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Clientes models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ClientesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
          $dataProvider->pagination = ['pageSize' => 8];

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Clientes model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Clientes model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Clientes();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->codigo_cliente]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Clientes model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->codigo_cliente]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Clientes model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
  public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['site/index']);
    }

     public function actionBaja($id)
    {
         Yii::$app->db->createCommand()
        ->update('clientes', ['baja'=>1], 'codigo_cliente='.$id)
        ->execute();
    return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }
    
    public function actionAlta($id)
    {
         Yii::$app->db->createCommand()
        ->update('clientes', ['baja'=>0], 'codigo_cliente='.$id)
        ->execute();
    return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }
    
       public function actionClientesopciones(){
        return $this->render('clientesopciones');
    
    }
    
         public function actionClientesenalta (){
        $dataProvider= new ActiveDataProvider([
            'query'=> Clientes::find()-> select("codigo_cliente, pais_cliente, cif_cliente, nombre_cliente")
            -> where ('baja=0'),
            'pagination'=>[
                'pageSize'=>5,
            ]
        ]);
        
        return $this-> render("clientesenalta",[
            "resultados"=>$dataProvider,
            "campos"=>['codigo_cliente', 'pais_cliente', 'cif_cliente', 'nombre_cliente'],
            "titulo"=> "CLIENTES DADOS DE ALTA",
             "enunciado"=> "CASO DE USO UTILIZANDO ORM",
            "sql"=> "SELECT * FROM proveedores WHERE baja IS FALSE ",
            
        ]);
     }
     
          public function actionClientesenbaja (){
        $dataProvider= new ActiveDataProvider([
            'query'=> Clientes::find()-> select("codigo_cliente, pais_cliente, cif_cliente, nombre_cliente")
            -> where ('baja=1'),
            'pagination'=>[
                'pageSize'=>5,
            ]
        ]);
        
        return $this-> render("clientesenbaja",[
            "resultados"=>$dataProvider,
            "campos"=>['codigo_cliente', 'pais_cliente', 'cif_cliente', 'nombre_cliente'],
            "titulo"=> "CLIENTES DADOS DE BAJA",
             "enunciado"=> "CASO DE USO UTILIZANDO ORM",
            "sql"=> "SELECT * FROM proveedores WHERE baja IS TRUE ",
            
        ]);
     }

    /**
     * Finds the Clientes model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Clientes the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Clientes::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
    
    public function actionClienteslogistica (){
        $dataProvider= new ActiveDataProvider([
            'query'=> Clientes::find()-> select("codigo_cliente, nombre_cliente, pais_cliente, cif_cliente")
            -> where ('baja=0'),
            'pagination'=>[
                'pageSize'=>5,
            ]
        ]);
        
        return $this-> render("clienteslogistica",[
            "resultados"=>$dataProvider,
            "campos"=>['codigo_cliente','nombre_cliente', 'pais_cliente', 'cif_cliente'],
            "titulo"=> "CLIENTES",
             "enunciado"=> "CASO DE USO UTILIZANDO ORM",
            "sql"=> "SELECT * FROM productos WHERE baja IS FALSE ",
            
        ]);
     }
     
     public function actionClienteslogisticabajas (){
        $dataProvider= new ActiveDataProvider([
            'query'=> Clientes::find()-> select("codigo_cliente, nombre_cliente, pais_cliente, cif_cliente")
            -> where ('baja=1'),
            'pagination'=>[
                'pageSize'=>5,
            ]
        ]);
        
        return $this-> render("clienteslogisticabajas",[
            "resultados"=>$dataProvider,
            "campos"=>['codigo_cliente','nombre_cliente', 'pais_cliente', 'cif_cliente'],
            "titulo"=> "CLIENTES",
             "enunciado"=> "CASO DE USO UTILIZANDO ORM",
            "sql"=> "SELECT * FROM productos WHERE baja IS FALSE ",
            
        ]);
     }
}

views/clientes/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Clientes */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="clientes-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'cif_cliente', ['template' => '{label}
<span title="El término CIF significa: Código de Identificación Fiscal.
Compuesto por 9 caracteres, responde al siguiente formato:
X99999999
La letra que incluye el código representa el tipo de sociedad a la que corresponde. 
Por ejemplo, “A” si es sociedad anónima, o “B”, si son sociedades de responsabilidad limitada. 
Además, de los dígitos que incluye, los dos primeros hacen referencia a la provincia o 
comunidad autónoma en la que se encuentra constituida dicha 
empresa o personalidad jurídica." class="glyphicon glyphicon-info-sign"></span>{input}'])->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'nombre_cliente', ['template' => '{label}
*{input}'])->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'tipo_empresa_cliente', ['template' => '{label}
<span title="Se requiere la forma jurídica de la empresa." class="glyphicon glyphicon-info-sign"></span>{input}'])->textInput(['maxlength' => true]) ?>
    
    
   <?= $form->field($model, 'sociedad_empresa_cliente')->textInput(['maxlength' => true]) ?>
       <?= $form->field($model, 'nombre_contacto_cliente')->textInput(['maxlength' => true]) ?>
       <?= $form->field($model, 'primer_apellido_contacto_cliente')->textInput(['maxlength' => true]) ?>
       <?= $form->field($model, 'segundo_apellido_contacto_cliente')->textInput(['maxlength' => true]) ?>
    
        <?= $form->field($model, 'pais_cliente', ['template' => '{label}
<span title="Se requieren la abreviatura equivalente al dominio de internet
correspondiente de cada país. Por ejemplo:
Reino Unido => UK. " class="glyphicon glyphicon-info-sign"></span>{input}'])->textInput(['maxlength' => true]) ?>
    


    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-marta-guardar']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/clientes/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ClientesSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="clientes-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'codigo_cliente') ?>

    <?= $form->field($model, 'pais_cliente') ?>

    <?= $form->field($model, 'cif_cliente') ?>

    <?= $form->field($model, 'nombre_cliente') ?>

    <?= $form->field($model, 'tipo_empresa_cliente') ?>

    <?php // echo $form->field($model, 'sociedad_empresa_cliente') ?>

    <?php // echo $form->field($model, 'nombre_contacto_cliente') ?>

    <?php // echo $form->field($model, 'primer_apellido_contacto_cliente') ?>

    <?php // echo $form->field($model, 'segundo_apellido_contacto_cliente') ?>

    <?php // echo $form->field($model, 'baja') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/clientes/clientesenbaja.php
<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
use yii\helpers\Html;

$this->title = 'Bajas de clientes';
$this->params['breadcrumbs'][] = ['label' => 'Agenda', 'url' => ['site/agenda']];
$this->params['breadcrumbs'][] = ['label' => 'Agenda: Clientes', 'url' => ['clientes/clientesopciones']];
$this->params['breadcrumbs'][] = $this->title;

?>

<div class="jumbotron">
    <h2><?=$titulo?></h2>
    
<!--    <p class="lead"> <?= $enunciado ?> </p>-->
<!--    <div class="well">
        <?= $sql ?>
        
    </div>-->
    
</div>

<div class="body-content">
    <div class="row">
        <div class="col-sm-6">
             <p>           
                      <?= Html::a('Contactar', ['clientes/index'], ['class' => 'btn btn-marta']) ?>
    </p>  
        </div>
       
        
    </div>
   
</div>

<?= \yii\grid\GridView::widget([
    'dataProvider'=> $resultados,
    'columns'=>$campos,
//    'options' => [ 'style' => 'background-color: whitesmoke; color:black;' ]
        ]);?>

views/clientes/clienteslogistica.php
<?php

/* @var $this yii\web\View */
/* @var $model app\models\Clientes */


use yii\helpers\Html;

$this->title = 'CLIENTES';
$this->params['breadcrumbs'][] = ['label' => 'Logística: Menú', 'url' => ['site/menulogistica']];
$this->params['breadcrumbs'][] = $this->title;

?>

    <div class="body-content">
        <br>
        <br>
        <div class="row">
            <div class="col-sm-4">
                <div class="thumbnail">
                     <?= Html::img('@web/images/clientes.png', ['alt' => 'My logo']) ?>
                    
                </div>
            </div>
            <div class="col-sm-8">
                
                <div class="thumbnail">
                    
                    <h1>CLIENTES</h1>
                    
                </div>
                
            </div>
        </div>
        
        <br>
        <br>
        
          <div class="row">
            
              <div class="col-sm-6">
             <p>
        <?= Html::a('Registrar un nuevo cliente', ['create'], ['class' => 'btn btn-marta']) ?>
        
                      <?= Html::a('Papelera', ['clientes/clienteslogisticabajas'], ['class' => 'btn btn-marta']) ?>
    </p>    
            </div>
        </div>
        
        <br>
        <br>
    </div>
  
<?= \yii\grid\GridView::widget([
    'dataProvider'=> $resultados,
    'columns' => [
//         ['class'=>'yii\grid\SerialColumn'],
//        'codigo_cliente',
         'nombre_cliente',
         'pais_cliente',
         'cif_cliente',
                ['class'=>'yii\grid\ActionColumn',
              'template' => '{view}, {baja}',
               'buttons' => [
            'view' => function ($url) {
              
                return Html::a('<span class="glyphicon glyphicon-eye-open"></span>',$url, [
                            'title' => Yii::t('app', 'lead-view')]);
            },
                    'baja' => function ($url) {
              
                return Html::a('<span class="glyphicon glyphicon-remove"></span>',$url, [
                            'title' => Yii::t('app', 'lead-baja'),
                    'data-confirm' => Yii::t('yii', 'Are you sure you want to update this item?'),
            'data-method'  => 'post']);
            }
            ],
                    'urlCreator' => function ($action, $model) {

    	if ($action === 'view') {

        	$url = './view?id='.$model['codigo_cliente'];

        	return $url;

    	}
        
        if ($action === 'baja') {

        	$url = './baja?id='.$model['codigo_cliente'];

        	return $url;

    	}

	}]
         ],
      
        ]);?>

views/clientes/clienteslogisticabajas.php
<?php

/* @var $this yii\web\View */
/* @var $model app\models\Clientes */


use yii\helpers\Html;

$this->title = 'CLIENTES: PAPELERA';
$this->params['breadcrumbs'][] = ['label' => 'Logística: Menú', 'url' => ['site/menulogistica']];
$this->params['breadcrumbs'][] = ['label' => 'CLIENTES', 'url' => ['clientes/clienteslogistica']];
$this->params['breadcrumbs'][] = $this->title;

?>

    <div class="body-content">
        <br>
        <br>
        <div class="row">
            <div class="col-sm-4">
                <div class="thumbnail">
                     <?= Html::img('@web/images/clientes.png', ['alt' => 'My logo']) ?>
                    
                </div>
            </div>
            <div class="col-sm-8">
                
                <div class="thumbnail">
                    
                    <h1>CLIENTES : PAPELERA</h1>
                    
                </div>
                
            </div>
        </div>
        <br>
        <br>
    </div>
  
<?= \yii\grid\GridView::widget([
    'dataProvider'=> $resultados,
    'columns' => [
//         ['class'=>'yii\grid\SerialColumn'],
//        'codigo_cliente',
         'nombre_cliente',
         'pais_cliente',
         'cif_cliente',
                  ['class'=>'yii\grid\ActionColumn',
              'template' => '{view}, {alta}, {delete}',
               'buttons' => [
            'view' => function ($url) {
              
                return Html::a('<span class="glyphicon glyphicon-eye-open"></span>',$url, [
                            'title' => Yii::t('app', 'lead-view')]);
            },
                    'alta' => function ($url) {
              
                return Html::a('<span class="glyphicon glyphicon-ok"></span>',$url, [
                            'title' => Yii::t('app', 'lead-alta'),
                    'data-confirm' => Yii::t('yii', 'Are you sure you want to update this item?'),
            'data-method'  => 'post']);
            },
                    'delete' => function ($url) {
              
                return Html::a('<span class="glyphicon glyphicon-trash"></span>',$url, [
                            'title' => Yii::t('app', 'lead-delete'),
                    'data-confirm' => Yii::t('yii', 'Are you sure you want to delete this item?'),
            'data-method'  => 'post']);
            }
            ],
                    'urlCreator' => function ($action, $model) {

    	if ($action === 'view') {

        	$url = './view?id='.$model['codigo_cliente'];

        	return $url;

    	}
        
         if ($action === 'alta') {

        	$url = './alta?id='.$model['codigo_cliente'];

        	return $url;

    	}
        if ($action === 'delete') {

        	$url = './delete?id='.$model['codigo_cliente'];

        	return $url;

    	}


	}]
         ],
      
        ]);?>

views/clientes/clientesopciones.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Html;
$this->title = 'Agenda: Clientes';
$this->params['breadcrumbs'][] = ['label' => 'Agenda', 'url' => ['site/agenda']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-index">

    
    <div class="body-content">

        <div class="colocacionbotonopciones">
           <div class="row">
        <div class="col-sm-6">
             <p>
                  <?= Html::a('Ver todos los clientes', ['clientes/index'], ['class' => 'btn btn-marta']) ?>
                      
    </p>  
        </div>
                    </div> 
        </div>
        <div class="opciones">
             
            <div class="row">
            
            <div class="col-sm-6">
           
                    <div class="caption">
                       <?= Html::img('@web/images/clientesenalta.jpg', ['alt' => 'My logo']) ?>
                         <?=Html::a ('Clientes en alta', ['clientes/clientesenalta'] ,['class'=> 'bottom-right'])?>
                    </div>
                    
                
                
            </div>
             <div class="col-sm-6">
                 
                    <div class="caption">
                        <?= Html::img('@web/images/clientesenbaja.jpg', ['alt' => 'My logo']) ?>
                           <?=Html::a ('Clientes en baja', ['clientes/clientesenbaja'] ,['class'=> 'bottom-right'])?>
                        
                  
                    
                </div>
                
            </div>
            
        </div> 
        </div>
       
           
    </div>
</div>

views/clientes/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Clientes */

$this->title = 'ALTA DE CLIENTE';
$this->params['breadcrumbs'][] = ['label' => 'Logística: Menú', 'url' => ['site/menulogistica']];
$this->params['breadcrumbs'][] = ['label' => 'CLIENTES', 'url' => ['clientes/clienteslogistica']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="clientes-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/clientes/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\ClientesSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Clientes';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="clientes-index">

      <br><!-- comment -->
        <br><!-- comment -->
          <h1><?= Html::encode($this->title) ?></h1>
  
                  <br><!-- comment -->
         
             <?= Html::a('NUEVO CLIENTE', ['clientes/create'], ['class' => 'btn btn-marta']) ?>

         <br><!-- comment -->
               <br><!-- comment -->
    

 

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

//            'codigo_cliente',
//            'pais_cliente',
//            'cif_cliente',
            'nombre_cliente',
//            'tipo_empresa_cliente',
            //'sociedad_empresa_cliente',
            //'nombre_contacto_cliente',
            //'primer_apellido_contacto_cliente',
            //'segundo_apellido_contacto_cliente',
            //'baja',

            ['class' => 'yii\grid\ActionColumn'],
        ],
//        'options' => [ 'style' => 'background-color: whitesmoke; color:black;' ]
    ]); ?>


</div>

views/clientes/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Clientes */

$this->title = 'Update Clientes: ' . $model->codigo_cliente;
$this->params['breadcrumbs'][] = ['label' => 'Clientes', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->codigo_cliente, 'url' => ['view', 'id' => $model->codigo_cliente]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="clientes-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/clientes/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Clientes */

$this->title = $model->nombre_cliente;
//$this->params['breadcrumbs'][] = ['label' => 'Clientes', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => 'Logística: Menú', 'url' => ['site/menulogistica']];
$this->params['breadcrumbs'][] = ['label' => 'CLIENTES', 'url' => ['clientes/clienteslogistica']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="clientes-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->codigo_cliente], ['class' => 'btn btn-marta']) ?>
<!--         Html::a('Delete', ['delete', 'id' => $model->codigo_cliente], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) -->
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'codigo_cliente',
            'pais_cliente',
            'cif_cliente',
            'nombre_cliente',
            'tipo_empresa_cliente',
            'sociedad_empresa_cliente',
            'nombre_contacto_cliente',
            'primer_apellido_contacto_cliente',
            'segundo_apellido_contacto_cliente',
//            'baja',
        ],
    ]) ?>

</div>